kriti_umiam/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mysite.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf.urls import url
from . import views

app_name = 'mysite'

urlpatterns = [
    url(r'^home/$', views.index, name='home'),
url(r'^$', views.index, name='home1'),
    #(r'^email/$', views.email, name='email'),
    url(r'^boarder/$', views.boarder, name='boarder'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^announcement/$', views.announcement, name='announcement'),
url(r'^blog/$', views.blog, name='blog'),
    url(r'^aboutus/$', views.aboutus, name='aboutus'),
    url(r'^award/$', views.award, name='award'),
    url(r'^printer/$', views.printer, name='printer'),
    url(r'^messmenu/$', views.messmenu, name='messmenu'),
url(r'^canteenmenu/$', views.canteenmenu, name='canteenmenu'),
    url(r'^addmessmenu/$', views.addmessmenu, name='addmessmenu'),
url(r'^addcanteenmenu/$', views.addcanteenmenu, name='addcanteenmenu'),
    #url(r'^home/$', views.index, name='index'),
    #url(r'^publications/$', views.publications, name='publications'),
    url(r'^deleteannouncement/(?P<pk>[0-9]+)/$', views.deleteannouncement, name='deleteannouncement'),
    url(r'^deletemessmenu/(?P<pk>[0-9]+)/$', views.deletemessmenu, name='deletemessmenu'),
url(r'^deletecanteenmenu/(?P<pk>[0-9]+)/$', views.deletecanteenmenu, name='deletecanteenmenu'),
    url(r'^deleteboarder/(?P<pk>[0-9]+)/$', views.deleteboarder, name='deleteboarder'),
    url(r'^deleteaward/(?P<pk>[0-9]+)/$', views.deleteaward, name='deleteaward'),
    url(r'^deletefile/(?P<pk>[0-9]+)/$', views.deletefile, name='deletefile'),
    url(r'^upvote/(?P<pk>[0-9]+)/$', views.upvote, name='upvote'),
    url(r'^downvote/(?P<pk>[0-9]+)/$', views.downvote, name='downvote'),        
    # url(r'^deleteexperience/(?P<pk>[0-9]+)/$', views.deleteexperience, name='deleteexperience'),
    # # url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    # # url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^createabout/$', views.createabout, name='createabout'),
    url(r'^clearall/$', views.del_database, name='clearall'),
    url(r'^clearallp/$', views.delprints, name='clearallp'),
    url(r'^createprinter/$', views.createprinter, name='createprinter'),
    url(r'^notes/$', views.notes, name='notes'),
    url(r'^deleteforprinter/(?P<pk>[0-9]+)/$', views.deleteforprinter, name='deleteforprinter'),
    url(r'^pay/$', views.pay, name='pay'),
    url(r'^notesupload/$', views.notesupload, name='notesupload'),   
    # url(r'^editabout/$', views.editabout, name='editabout'),
    # url(r'^aboutto/(?P<user_name>.*)/$',views.aboutto,name='aboutto'),
    # url(r'^todolist/$', views.todolist, name='todolist'),
    # url(r'^createeducation/$', views.createeducation, name='createeducation'),
    # url(r'^education/$', views.education, name='education'),
    # url(r'^teaching/$', views.teaching, name='teaching'),
    url(r'^addannouncement',views.addannouncement,name="addannouncement"),
    url(r'^addboarder',views.addboarder,name="addboarder"),
    url(r'^addaward',views.addaward,name="addaward"),
    url(r'^registerprinter/',views.registerprinter,name="registerprinter"),
    url(r'^getprints/',views.getprints,name="getprints"),
    # url(r'^createexperience/$', views.createexperience, name='createeducation'),
    # url(r'^createtodo/$', views.createtodo, name='createtodo'),
    # url(r'^experience/$', views.experience, name='education'),
    # url(r'^deletetodo/(?P<pk>[0-9]+)/$', views.deletetodo, name='deletetodo'),
    # url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    # url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    # url(r'^(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    # url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
 url(r'^upload/$', views.upload_file, name='upload'),

]

mysite/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import About,Award,Announcement,Doctake,Boarder,Filler,Note,Messmenu,Canteenmenu
from .choices import *
import datetime
from django.forms.extras.widgets import SelectDateWidget
from datetime import datetime
date_range = 100    
this_year = datetime.now().year
from django.forms import extras
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','email','password']

class AboutForm(forms.ModelForm):
    birth_date= forms.DateField(widget=extras.SelectDateWidget(years=range(this_year - date_range, this_year)))
    class Meta:
        model = About
        fields = ['name','birth_date','position', 'dept','image','email','telephone','roomnumber','authentication_key']

class AnnouncementForm(forms.ModelForm):

    class Meta:
        model = Announcement
        fields = ['info','title','date']

class AwardForm(forms.ModelForm):

    class Meta:
        model = Award
        fields = ['detail','position','year']

class DocForm(forms.ModelForm):
    hostel = forms.ChoiceField(choices = HOSTEL_CHOICES, required=True)
    class Meta:
        model = Doctake
        fields = ['doc','hostel']

class BoarderForm(forms.ModelForm):

    class Meta:
        model = Boarder
        fields = ['name','roomnumber','rollnumber','dept','telephone']

class FillerForm(forms.ModelForm):

    class Meta:
        model = Filler
        fields = ['name','phonenumber','hostel']


class NoteForm(forms.ModelForm):

    class Meta:
        model = Note
        fields= ['material','year','Course_code']

class MessmenuForm(forms.ModelForm):

    class Meta:
        model=Messmenu
        fields = ['image','date']

class CanteenmenuForm(forms.ModelForm):

    class Meta:
        model=Canteenmenu
        fields = ['image','date']

mysite/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse,HttpResponse
from django.shortcuts import render,redirect, get_object_or_404
# Create your views here.
from .models import Announcement,Award,About,Boarder,Doctake,Filler,Note,Messmenu,Canteenmenu
from .forms import UserForm,AboutForm,AnnouncementForm,AwardForm,DocForm,BoarderForm,FillerForm,NoteForm,MessmenuForm,CanteenmenuForm
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']
from django.contrib.auth.models import User
import PyPDF2
import os
from collections import OrderedDict as od
import datetime

def aboutus(request):
    info2=About.objects.all().filter(authentication_key="secretary")
    context={'info2':info2}
    return render(request,'mysite/aboutus.html',context)



def pay(request):
    info=Doctake.objects.filter(user=request.user)
    dic={}

    ac=os.getcwd()
    b=ac+'/Umiam-Hostel-Website'
    for x in info:
        a=x.hostel
        file_name = x.doc.url
        file_name=b+file_name
        pdf_file = open(file_name)
        read_pdf = PyPDF2.PdfFileReader(pdf_file)
        cost=read_pdf.getNumPages()      
        if a in dic.keys():
            dic[a]=dic[a]+cost
        else:
            dic[a]=cost
        x.paid="yes"
        x.save()

    context={
        "dic":dic
    }
    return render(request,'mysite/confirmpayment.html',context)


def boarder(request):
    info = Boarder.objects.all()
    if request.user.is_authenticated():
        temp = Filler.objects.filter(user=request.user)
    if request.user.is_authenticated() and temp.count()==0:
        abo=About.objects.filter(user=request.user)
        for x in abo:
            abou=x.authentication_key     
        context = {
            "info": info,
            "abou" : abou
        }
    else:
        context = {
            "info": info,
         }
    return render(request, 'mysite/boarder.html', context)

def upload_file(request):
    if not request.user.is_authenticated():
        return render(request, 'mysite/login.html')
    temp = Filler.objects.filter(user=request.user)
    if temp.count()!=0:
        return redirect('/getprints/')

    else:
        form = DocForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            info = form.save(commit=False)
            info.user = request.user
            info.doc = request.FILES['doc']
            info.title = info.doc.name

            index = form.cleaned_data.get('hostel')
            info.hostel = dict(form.fields['hostel'].choices)[index]
            # file_type = info.image.url.split('.')[-1]
            # file_type = file_type.lower()
            # if file_type not in IMAGE_FILE_TYPES:
            #     context = {
            #         'info': info,
            #         'form': form,
            #         'error_message': 'Image file must be PNG, JPG, or JPEG',
            #     }
            #     return render(request, 'mysite/aboutform.html', context)
            info.save()
            return redirect('/upload/')
        context = {
            "form": form,
        }
        return render(request, 'mysite/uploadform.html', context)

def getprints(request):
    fir=Filler.objects.get(user=request.user)
    lis = Doctake.objects.filter(hostel=fir.hostel).filter(paid="yes")
    context={
        "lis":lis,
    }
    return render(request,'mysite/orders.html',context)

def deleteforprinter(request,pk):
    fir=Doctake.objects.get(id=pk)
    fir.paid="No"
    fir.save()
    return redirect('/getprints/')

def delprints(request):
    fir = Filler.objects.get(user=request.user)
    lis = Doctake.objects.filter(hostel=fir.hostel)
    for x in lis:
        x.paid="no"
        x.save()
    return redirect('/getprints/')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'mysite/login.html', context)

def index(request):
    dat = datetime.date.today()
    use = About.objects.all()
    d = {}
    for x in use:
        dat_user = x.birth_date
        if dat.day == dat_user.day and dat.month == dat_user.month:
            d[(dat.year-dat_user.year)]=x.name
    context = {
        "d" : d,
    }
    return render(request,'mysite/index.html',context)

def announcement(request):
    info1=Announcement.objects.all()
    if request.user.is_authenticated():
        temp = Filler.objects.filter(user=request.user)
    if request.user.is_authenticated() and temp.count()==0:
        abo=About.objects.filter(user=request.user)
        for x in abo:
            abou=x.authentication_key

        context={
            "info1":info1,
            "abou":abou
        }
    else:
        context = {
		  "info1": info1,
	   }
    return render(request,'mysite/announcement.html', context)

def notesupload(request):
    if not request.user.is_authenticated():
        return render(request, 'mysite/login.html')
    else:
        temp = Filler.objects.filter(user=request.user)
        if temp.count()==0 :
            form = NoteForm(request.POST or None, request.FILES or None)
            if form.is_valid():
                info = form.save(commit=False)
                info.user = request.user
                info.material = request.FILES['material']
                info.title=info.material.name
                info.save()
                return redirect('/notes/')
            context = {
                "form": form,
            }
            return render(request, 'mysite/aboutform.html', context)
        else :
            return HttpResponse('SORRY NOTE HUB UPLOAD FEATURE NOT FOR PRINTERS!!!!!')

def award(request):
    info1=Award.objects.all()
    if request.user.is_authenticated():
        temp = Filler.objects.filter(user=request.user)
    if request.user.is_authenticated() and temp.count()==0:
        abo=About.objects.filter(user=request.user)
        for x in abo:
            abou=x.authentication_key
        
        context = {
    		"info1": info1,
            "abou" : abou
    	}
    else:
        context = {
            "info1": info1,
         }

    return render(request,'mysite/award.html', context)

def addannouncement(request):
    if not request.user.is_authenticated():
        return render(request, 'mysite/login.html')
    else:
        form = AnnouncementForm(request.POST or None)
        if form.is_valid():
            info = form.save(commit=False)
            #info.user = request.user
            info.save()
            return redirect('/announcement/')
        context = {
            "form": form,
        }
        return render(request, 'mysite/aboutform.html', context)

def addboarder(request):
    if not request.user.is_authenticated():
        return render(request, 'mysite/login.html')
    else:
        form = BoarderForm(request.POST or None)
        if form.is_valid():
            info = form.save(commit=False)
            #info.user = request.user
            info.save()
            return redirect('/boarder/')
        context = {
            "form": form,
        }
        return render(request, 'mysite/aboutform.html', context)

def addaward(request):
    if not request.user.is_authenticated():
        return render(request, 'mysite/login.html')
    else:

        form = AwardForm(request.POST or None)
        if form.is_valid():
            info = form.save(commit=False)
            #info.user = request.user
            info.save()
            return redirect('/award/')
        context = {
            "form": form,
        }
        return render(request, 'mysite/aboutform.html', context)

def deleteannouncement(request,pk):
    instance = Announcement.objects.get(id=pk)
    instance.delete()
    return redirect('/announcement/')

def deleteaward(request,pk):
    instance = Award.objects.get(id=pk)
    instance.delete()
    return redirect('/award/')

def deleteboarder(request,pk):
    instance = Boarder.objects.get(id=pk)
    instance.delete()
    return redirect('/boarder/')

def deletefile(request,pk):
    instance = Doctake.objects.get(id=pk)
    instance.doc.delete()
    instance.delete()
    return redirect('/printer/')

def del_database(request):
    files = Doctake.objects.filter(user=request.user)
    for f in files:
        f.doc.delete()
        f.delete()
    return redirect('/printer/')


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/home/')
            else:
                return render(request, 'mysite/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'mysite/login.html', {'error_message': 'Invalid login'})
    return render(request, 'mysite/login.html')


def notes(request):
    if not request.user.is_authenticated():
        return render(request, 'mysite/login.html')    
    if request.method == "POST":
        search=request.POST.get('code',None)
        info=Note.objects.filter(Course_code=search)
        l = od()
        for x in info:
            use = About.objects.filter(user=x.user)
            for j in use:
                l[x]=j

        context={
            "info":info,
            'l' : l,
        }
        return render(request,'mysite/notesform.html',context)
    return render(request, 'mysite/notesform.html')

def register(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        # form.email = request.POST['Email']
        # form.password = request.POST['password']
        # form.username = request.POST['username']
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']

mysite/templates/mysite/a.html
<!DOCTYPE HTML>
<html>
<head>
<title>
Title</title></head>
<body>
hello world
</body>
</html>

mysite/templates/mysite/canteenmenu.html
{%  load staticfiles  %}

<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<title>Menu</title>
	<link rel="stylesheet" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" />
	<link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,700,300italic' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}" />
	<link rel="stylesheet" href="{% static 'css/animat/animate.min.css' %}" />
	<link rel="stylesheet" href="{% static 'css/fancybox/jquery.fancybox.css' %}" />
	<link rel="stylesheet" href="{% static 'css/nivo-lightbox/nivo-lightbox.css' %}" />
	<link rel="stylesheet" href="{% static 'css/themes/default/default.css' %}" />
	<link rel="stylesheet" href="{% static 'css/owl-carousel/owl.carousel.css' %}" />
	<link rel="stylesheet" href="{% static 'css/owl-carousel/owl.theme.css' %}" />
	<link rel="stylesheet" href="{% static 'css/owl-carousel/owl.transitions.css' %}" />
	<link rel="stylesheet" href="{% static 'css/style2.css' %}" />
	<link rel="stylesheet" href="{% static 'css/responsive2.css' %}" />


</head>
<body style="background-color:black;">

{% if user.is_authenticated and abo|stringformat:"s" == "secretary" %}
	<div class="head_title text-center wow slideInLeft" data-wow-duration="1.5s">
    <div class="text-right"><h4><a href="/addcanteenmenu/"><button style="color: grey;">Add Canteen Menu</button></a></h4></div>
    </div>
{% endif %}
	<div class='preloader'><div class='loaded'>&nbsp;</div></div>		
	
	<section id="special" class="special sections">
		<div class="container">
			<div class="row">
				<div class="head_title text-center wow slideInLeft" data-wow-duration="1.5s">
					<h2>This month's Special</h2>
					<div class="separetor"></div>
				</div>
				    {% for field in info %}

				<div class="main_special text-center wow slideInUp" data-wow-duration="3s">
										<h3>Canteen menu(updated on {{field.date}} )</h3>
										<img src="{{field.image.url}}">
        	{% if user.is_authenticated and abo|stringformat:"s" == "secretary" %}
            <h4><a href="/deletecanteenmenu/{{field.id}}" style="color: red;">Delete</a></h4>
        {% endif %}
				</div>	
					{% endfor %}
			</div>
		</div>
	</section>



	<!-- STRAT SCROLL TO TOP -->
	
	<div class="scrollup">
		<a href="#"><i class="fa fa-chevron-up"></i></a>
	</div>
	
	
	
	
	

	<script type="text/javascript" src="{% static 'js/jquery/jquery.js' %}"></script>
	
	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
	
	<script type="text/javascript" src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
	
	<script type="text/javascript" src="{% static 'js/fancybox/jquery.fancybox.pack.js' %}"></script>
	
	<script type="text/javascript" src="{% static 'js/nivo-lightbox/nivo-lightbox.min.js' %}"></script>
	
	<script type="text/javascript" src="{% static 'js/owl-carousel/owl.carousel.min.js' %}"></script>
	
	
	
	<script type="text/javascript" src="{% static 'js/jquery-easing/jquery.easing.1.3.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/wow/wow.min.js' %}"></script>
</body>
</html>

mysite/templates/mysite/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html >
<head>

  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <title>Login</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
<style type="text/css">
	#login{
		margin-top:100px;
	}
	#mainbody{
		background-color: #FED8B1;
	}
    <script src='https://www.google.com/recaptcha/api.js'></script>
</style>
</head>

<body>
  <body id="mainbody">
<div class="container" id="login">
	<section id="content">
		{% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
            {% endif %}
		<form class="form-horizontal" role="form" action="{% url 'mysite:login_user'%}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<h1>Login Form</h1>
			<div>
				<input type="text" placeholder="Username" required="" id="username" name="username"/>
			</div>
			<div>
				<input type="password" placeholder="Password" required="" id="password" name="password"/>
			</div>
            <div class="g-recaptcha" data-sitekey="6LeHpTcUAAAAALTXhAOfpl8xLyJKdOsw_ppm-ltS"></div>
			<div>
				<input type="submit" value="Log in" />
				<a href="{% url 'mysite:home' %}">Back to home</a>
				<a href="{% url 'mysite:register' %}">Register</a>
			</div>
		</form><!-- form -->
	</section><!-- content -->
</div><!-- container -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</body>

    <script  src=href="{% static 'js/index.js' %}"></script>

</body>
</html>

mysite/templates/mysite/messmenu1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

</head>
<body>
{% if user.is_authenticated and abo|stringformat:"s" == "secretary" %}
    <h2><a href="/addmessmenu/">Add announcement</a> </h2>
{% endif %}
    {% for field in info %}
        <h1>Mess menu(updated on {{field.date}} )</h1>
        <img src="{{field.image.url}}">
        {% if user.is_authenticated and abo|stringformat:"s" == "secretary" %}
            <h4><a href="/deletemessmenu/{{field.id}}">Delete</a></h4>
        {% endif %}
    {% endfor %}
</body>
</html>

mysite/templates/mysite/registerform.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <title>registerationform</title>
      <link rel="stylesheet" href="{% static 'css/register.css' %}">
	<style type="text/css">
		.fff
		{
			position:relative;
			left:600px;
			top:300px;
		}

	</style>

</head>

<body>
<div id="qe">
<input id="inp" type="text" name="key" class="fff" style="font-size:18px">
<button type="submit" class="btn btn-primary fff" onclick="f()">AUTHENTICATE</button>
</div>

<div id="we" style="display:none;">
<form action="{% url 'mysite:register'%}" method="post">
	{% csrf_token %}
  <h2>Register</h2>
  		<p>
			<label for="Email" class="floatLabel">Username</label>
			<input id="Email" name="username" type="text">
		</p>
		<p>
			<label for="Email" class="floatLabel">WebMail</label>
			<input id="Email" name="Email" type="text">
		</p>
		<p>
			<label for="password" class="floatLabel">Password</label>
			<input id="password" name="password" type="password">
			<span>Enter a password longer than 8 characters</span>
		</p>
		<p>
			<label for="confirm_password" class="floatLabel">Confirm Password</label>
			<input id="confirm_password" name="confirm_password" type="password">
			<span>Your passwords do not match</span>
		</p>
		<p>
			<input type="submit" value="Create My Account" id="submit">
		</p>

	</form></div>


		<section id="bottom">
        <div class="container wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="widget">
                        <h3><a href="http://intranet.iitg.ernet.in/noticeboard/">Notice board</a></h3>

                    </div>    
                </div><!--/.col-md-3-->

                <div class="col-md-3 col-sm-6">
                    <div class="widget">
                        <h3><a href="https://webmail.iitg.ernet.in/src/login.php">Webmail</a></h3>

                    </div>    
                </div><!--/.col-md-3-->

                <div class="col-md-3 col-sm-6">
                    <div class="widget">
                        <h3><a href="http://www.iitg.ernet.in/acad/acadCal/academic_calander.htm" style="color:black;">Academic Calendar</a></h3>

                    </div>    
                </div><!--/.col-md-3-->

                <div class="col-md-3 col-sm-6">
                    <div class="widget">
                        <h3><a href="http://www.iitg.ac.in/aa/pages/campusmap/index.php?hq">Campus Map</a></h3>

                    </div>    
                </div><!--/.col-md-3-->
            </div>
        </div>
    </section><!--/#bottom-->


	<script>
	function f(){
	var x=document.getElementById("inp").value;
	if (x=="normal" || x=="secy")
	{
		document.getElementById("qe").style.display="none";
		document.getElementById("we").style.display="block";

	}
	else if(x=="printer")
	{
		window.location.href = '/registerprinter/';
	}







	}


	</script>



  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script  src="{% static 'js/register.js' %}"></script>
</body>
</html>

mysite/templates/mysite/registerprinter.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>registerationform</title>
      <link rel="stylesheet" href="{% static 'css/register.css' %}"

</head>

<body>
<!-- <div id="qe">
<input id="inp" type="text" name="key">
<button type="submit" onclick="f()">AUTHENTICATE</button>
</div> -->

<div id="we" style="display:block;">
<form action="{% url 'mysite:registerprinter'%}" method="post">
	{% csrf_token %}
  <h2>Register</h2>
  		<p>
			<label for="Email" class="floatLabel">Username</label>
			<input id="Email" name="username" type="text">
		</p>
		<p>
			<label for="Email" class="floatLabel">WebMail</label>
			<input id="Email" name="Email" type="text">
		</p>
		<p>
			<label for="password" class="floatLabel">Password</label>
			<input id="password" name="password" type="password">
			<span>Enter a password longer than 8 characters</span>
		</p>
		<p>
			<label for="confirm_password" class="floatLabel">Confirm Password</label>
			<input id="confirm_password" name="confirm_password" type="password">
			<span>Your passwords do not match</span>
		</p>
		<p>
			<input type="submit" value="Create My Account" id="submit">
		</p>

	</form></div>

<!-- 	<script>
	function f(){
	var x=document.getElementById("inp").value;
	if (x=="normal" || x=="secy")
	{
		document.getElementById("qe").style.display="none";
		document.getElementById("we").style.display="block";

	}
	else if(x=="printer")
	{
		window.location.href = '/registerprinter/';
	}







	}
	</script> -->



  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script  src="{% static 'js/register.js' %}"></script>
</body>
</html>